name: GCP Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    environment: GCP
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Deploy to GCF
        run: |
          gcloud functions deploy protector-app-bot \
            --runtime nodejs12 \
            --allow-unauthenticated \
            --trigger-http \
            --entry-point probotApp \
            --set-env-vars APP_ID="${{secrets.APP_ID}}",PRIVATE_KEY="${{secrets.PRIVATE_KEY}}",WEBHOOK_SECRET="${{secrets.WEBHOOK_SECRET}}"
