name: Test
on:
  workflow_run:
    workflows: [GCP Deploy]
    types: [completed]
    
jobs:
  on-success:
      runs-on: ubuntu-latest
      steps:
        - name: Recreate test repo
          run: |
            gh repo delete  Sankhe-LLC/testrepo101 --confirm
            gh repo create  Sankhe-LLC/testrepo101 --public -l "MIT"
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
